### PR TITLE
Add getLatestTestIdByEngagementName

### PR DESCRIPTION
**Pull request by wurstbrot**

### CODE REVIEW

**Comment by J12934** [comment]
Test are currently failing to to https://github.com/jeremylong/DependencyCheck/issues/2403

Will take a look at the PR once that is fixed.

**Comment by wurstbrot** [comment]
Looks like there is no 2020 CVE and therefore Dep. Check fails:
`[INFO] Finished at: 2020-01-02T14:47:49Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.owasp:dependency-check-maven:5.2.2:aggregate (default) on project securecodebox-parent: Fatal exception(s) analyzing SecureCodeBox Engine: One or more exceptions occurred during analysis:
[ERROR] 	Unable to download meta file: https://nvd.nist.gov/feeds/json/cve/1.0/nvdcve-1.0-2020.meta; received 404 -- resource not found
[ERROR] 	No documents exist`

**Comment by wurstbrot** [comment]
Can you re-trigger https://travis-ci.com/secureCodeBox/engine/builds/142888354 , it should work now (see https://nvd.nist.gov/vuln/data-feeds#JSON_FEED).

**Comment by J12934** [comment]
Re triggering the CI unfortunately wasn't quite enough.
We had some DependencyCheck suppression which were only active until the first of January.
Spend some time to fix these now. Will merge once travis passes 👍

**Pull request merged**
